### ISSUE TITLE
Kütüphane kurulumu hakkında

### ISSUE THREAD

**Issue by uykusuzz35** [dlenettr/amp#1]
Hocam ilk adımda verdiğiniz kodu nerede ve nasıl çalıştırıyoruz. amp-library klasörünü oluşturdum ama kodu nasıl çalıştıracağımı bilemiyorum. Yardımcı olursanız sevinirim.

**Comment by dlenettr** [comment]
composer yükleyerek gerekli dosyaları indirebilirsiniz. Kurulum hakkında Google'dan araştırma yapabilirsiniz

**Comment by dlenettr** [comment]
AMP kütüphanesi zip olarak eklendi. Açıklamalardan kurulumu hakkında bilgi edinebilirsiniz
