### ISSUE TITLE
Lazy Image

### ISSUE THREAD

**Issue by tolgaaaltas** [dlenettr/amp#2]
DLE v.13.2 ile gelen Lazy Image özelliğini aktif ettiğimizde AMP sürümünde görseller hiç yüklenmiyor. Henüz yeni yükseltme yaptığım için Lazy Image'in çalışma mantığına göz atıp düzenlemenin nasıl yapılabileceğine göz atamadım.

**Comment by dlenettr** [comment]
Teşekkürler. Sorun giderildi.

**Comment by tolgaaaltas** [comment]
Öncelikle vakit ayırıp düzenleme gerçekleştirdiğin için teşekkürler Mehmet. Eklentiyi güncelledim ancak PHP'de yaptığın düzenleme AMP standartlarına uygun olarak resim çıkışı vermediği için AMP sayfasında görseller gözükmüyor. Görsel HTML içerisinde böyle kodlanmış:
`<img class="fr-dib" alt="" data-src="https://msfthaber.com/uploads/posts/2019-03/medium/1551799760_edge-extentions.jpg">`

Ancak AMP'te gözükmesi için şu şekilde olması gerekiyor:
`<amp-img src="https://msfthaber.com/uploads/posts/2019-03/medium/1551799760_edge-extentions.jpg"></amp-img>`

Şimdiden tekrar teşekkürler vakit ayırdığın için.

**Comment by tolgaaaltas** [comment]
Bende herhalde bir sorun var çünkü amp-img'a dönüştürmüyor etiketleri. Başka kullanan varsa o da yazsaydı iyi olurdu durumu.

**Comment by dlenettr** [comment]
@tolgaaaltas Son yaptığım düzenlemeyi uygulayabilirsin.. Dönüştürme işlemi için ekleme yaptım. Sonucu bildirirsen sevinirim.

**Comment by tolgaaaltas** [comment]
Son yaptığın düzenlemeyi anında uyguladım büyük bir heyecanla, vakit ayırıp düzenlediğin için tekrar teşekkür ederim. Ancak makalelerin içerisinde yer alan resimleri (ilave alanı elle eklediğim için sorun yok) AMP standardına çevirmediği için AMP olarak sonuçlarda çıkarmıyor. Örnek sayfa: https://msfthaber.com/uygulamalar/1110-yeni-chromium-tabanli-edgee-ait-ekran-goruntuleri-sizdirildi/amp.html

**Comment by dlenettr** [comment]
1) Öncelikle metrika için kullandığın json hatalı.. PHP deki gibi yorum satırları olmamalı. https://jsonlint.com/ Buradan kontrol edebilirsin.
2) Yeni bir bul-değiştir ekledim. Desene takılmayan veriler varmış..

**Comment by tolgaaaltas** [comment]
Maalesef bir değişiklik yaşanmadı yine. Hala amp-img'a dönüştürmüyor Lazy Image aktif olduğunda. Aslında bu sefer her şey normal, dönüştürme sağlanıyor ancak sonuna </amp-img> eklemediği için görsel çıkmıyor.

**Comment by canyesilyurt** [comment]
<amp-img sorunu bendede mevcut. Lazy image aktifken de kapalıyken de img etiletlerini amp-img'ye otomatik çevirmiyor.
